### ISSUE TITLE
bykc.py is no longer valid after the 2022 BOYA Subject System update

### ISSUE THREAD

**Issue by Errno1024** [Errno1024/BUAA-Course-Grab#3]
The 2022 update caused bykc.py to be no longer valid. This issue is because the system uses a sort of encryption to hide the plain text information.

Before the update, one can simply get all information through the response content. Taking `getUserProfile` API as an example, the response is a JSON plain text containing following information.
```json
{
    "id": 1,
    "employeeId": "10000000",
    "realName": "Xxx",
    "term": {
        "id": 1,
        "termName": "xxx",
        "delFlag": 0
    },
    "college": {
        "id": 1,
        "collegeName": "xxx",
        "delFlag": 0
    },
    "role": {
        "id": 1,
        "roleName": "xxx",
        "delFlag": 0
    },
    "studentNo": "10000000",
    "noticeSwitch": false,
    "delFlag": 0,
    "ipAddress": "10.0.0.1"
}
```
After the update, the content is encrypted and it returns something like this:
```
eqkYr4Qu8kGGoN0yNCoD8Z==
```
The encryption uses multiple methods to enhance the security. The source code, `app.45ee6b90bb55fde60482.js`, contains some code as follows:
```javascript
// ...
var sign = (0,
_sha2.default)(paramsString).toString()
  , signEncrypt = jSEncrypt.encrypt(sign)
  , aesKey = UtilService.getRandomStr(16)
  , aesKeyJSEncrypt = jSEncrypt.encrypt(aesKey)
  , key = _encUtf2.default.parse(aesKey)
  , paramsEncrypt = _aes2.default.encrypt(_encUtf2.default.parse(paramsString), key, {
    iv: key,
    mode: _modeEcb2.default,
    padding: _padPkcs2.default
}).toString()
  , timestamp = (new Date).getTime() + "";
headers.sk = signEncrypt,
headers.ak = aesKeyJSEncrypt,
headers.ts = timestamp;
var decryptResponse = function(response) {
    var key = _encUtf2.default.parse(aesKey)
      , data = _aes2.default.decrypt(response.data, key, {
        iv: key,
        mode: _modeEcb2.default,
        padding: _padPkcs2.default
    })
      , plainDataString = _encUtf2.default.stringify(data);
// ...
  , startRequest = function() {
    $http.post(apiURL, paramsEncrypt, {
        headers: headers,
        cache: !1,
        timeout: 1e3 * options.requestTimeout
    }).then(function(result) {
        result = decryptResponse(result),
        callSuccessFunction(result)
    }, function(err) {
        err = decryptResponse(err),
        callErrorFunction(err)
    })
};
startRequest()
// ...
```
The method first generates a random string `aesKey` as the key used in AES encryption, and then the key and parameters are parsed by an unknown module `_encUtf`, which is packed by Webpacker and hard to find the source code (it's probably a module that converts strings to their UTF-8 version), and the parameters are encrypted by AES using the parsed key. The key and parameters (encoded by SHA) are also encrypted by RSA algorithm, with a public key:
```
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDlHMQ3B5GsWnCe7Nlo1YiG/YmHdlOiKOST5aRm4iaqYSvhvWmwcigoyWTM+8bv2+sf6nQBRDWTY4KmNV7DBk1eDnTIQo6ENA31k5/tYCLEXgjPbEjCK9spiyB62fCT6cqOhbamJB0lcDJRO6Vo1m3dy+fD0jbxfDVBBNtyltIsDQIDAQAB
```
and are contained in headers.

When the request is received, the server will use the RSA private key to decrypt the AES key, and use the key to decrypt the parameters in the payload. The SHA result of parameters will be used to verify the parameters. The server will reply with a response contains cipher text encrypted by AES using identical key.

Technically, the process can be fully simulated, but to be honest, following the process and testing can be really annoying, so I'm not intended to fix the problem recently. I'd be really grateful if someone can help me fix it.

**Comment by taozhuo2000** [comment]
what a pity if we cannot use it!!!

**Comment by Errno1024** [comment]
Thanks to the solution in [https://github.com/Dr-Bluemond/BuaaBykcCrawler](https://github.com/Dr-Bluemond/BuaaBykcCrawler), the latest code is still under test, but the problem is now fixed.
